
tasks:
  - name: Terminal
github:
    prebuilds:
        master: true
        branches: true
image:
    file: .gitpod.Dockerfile
vscode:
  extensions:
    - rebornix.ruby
    - bierner.markdown-preview-github-styles
    - vscode.markdown-notebook-math
    - KnisterPeter.vscode-github
    - ban.spellright
    - notZaki.pandocciter
    - mathiassoeholm.markdown-link-updater
