tasks:
  - name: Initialize
    before: |2
      cd /workspace/dclements.github.io/docs
    init: |2
      bundle update
      bundle install
    command: bundle exec jekyll serve
  - name: Terminal
github:
    prebuilds:
        master: true
        branches: true
image:
    file: .gitpod.Dockerfile
ports:
  - port: 4000
    onOpen: open-browser
    visibility: private
vscode:
  extensions:
    - rebornix.ruby
    - bierner.markdown-preview-github-styles
    - vscode.markdown-notebook-math
    - KnisterPeter.vscode-github
    - ban.spellright
    - notZaki.pandocciter
    - mathiassoeholm.markdown-link-updater
    - wingrunr21.vscode-ruby
