
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: LaTeX auto-rebuild
    command: >
      while find . -name '*.tex' | xargs inotifywait -qqre modify .; do         latexmk -pdf ;       done
  - name: Terminal
github:
    prebuilds:
        master: true
        branches: true
image:
    file: .gitpod.Dockerfile
vscode:
  extensions:
    - rebornix.ruby
    - bierner.markdown-preview-github-styles
    - vscode.markdown-notebook-math
    - efoerster.texlab
    - James-Yu.latex-workshop
    - JeffersonQin.latex-snippets-jeff
    - KnisterPeter.vscode-github
    - ban.spellright
    - notZaki.pandocciter
    - mathiassoeholm.markdown-link-updater
