title: Organizing Software
tagline: "Better engineering through engineering"
description: >-
  Misc thoughts on organizing, software, LARP, gender, and everything inbetween.
jekyll_baseurl: ""
domain: dclements.github.io
url: https://dclements.github.io
markdown: kramdown
twitter:
  username: waterpriciple
github:
  username: dclements
repository: dclements/dclements.github.io
timezone: America/Denver
encoding: UTF-8
lang: en

theme: jekyll-theme-chirpy
theme_mode: dark
paginate: 1
paginate_path: "/posts/page/:num"
toc: true
future: false

avatar:

social:
  name: DHC
  email: dclements@users.noreply.github.com
  links:
    - https://github.com/dclements
    - https://twitter.com/waterprinciple
    - https://www.linkedin.com/in/dhclements

scholar:
  style: association-for-computing-machinery

# Build settings
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-spaceship
  - kramdown
 
# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: './'
      type: posts
    values:
      layout: home
      comments: false
      toc: false
  - scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      comments: false 
      toc: true 
      permalink: /categories/:slugified_categories/posts/:slug
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - LICENSE*
  - gulpfile.js
  - node_modules
  - package*.json
  - .keep

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
