source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!

gem "jekyll", "~> 4.2.2"

gem 'jekyll-theme-chirpy', '~> 5.1.0'

group :jekyll_plugins do
  gem 'jekyll-default-layout', '~> 0.1'
  gem "jekyll-feed", "~> 0.16"
  gem 'jekyll-optional-front-matter', '~> 0.3.2'
  gem 'jekyll-regex-replace', '~> 1.1'
  gem 'jekyll-scholar', '~> 7.1'
  gem 'jekyll-sitemap', '~> 1.4'
  gem 'jekyll-spaceship', '~> 0.10', '>= 0.10.2'
  gem 'kramdown', '~> 2.4'
end

gem "webrick", "~> 1.7"

# Due to a security vulnerability in earlier versions
gem "nokogiri", ">= 1.13.8"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
